### ISSUE TITLE
Franken-pull-parser python adaptation trouble

### ISSUE THREAD

**Issue by ebeshero** [djbpitt/raising#1]
My adaptation of the Frankenstein pull parser is missing something important, or it wouldn't be outputting attributes on the newly constructed end-tags. See the python file in this commit: https://github.com/djbpitt/raising/commit/792bd0b3f62ac4d1b5c6f0999d05b18d69f4c6b6 

Can anyone spot what I've neglected here?

**Comment by djbpitt** [comment]
I need to quit for the night, but I’ll fix this in the morning and close the issue when I've done that.

**Comment by djbpitt** [comment]
Fixed!
